<?php

namespace Database\Factories;

use App\Models\Game; // Game model
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Carbon; // For date manipulation

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Game>
 */
class GameFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    protected $model = Game::class; // Link to the Game model

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Define how to generate fake data for each field based on schema
        $prefectures = ['北海道', '青森県', /* ... all 47 ... */ '沖縄県']; //
        $statuses = ['募集中', '満員', '開催済み', '中止']; //

        $status = fake()->randomElement($statuses);
        $capacity = fake()->numberBetween(18, 50); // Capacity between 18 and 50

        return [
            // game_id is automatically generated by the model's boot method
            'place_name' => fake('ja_JP')->city . '野球場', // Fake Japanese place name
            'game_date_time' => Carbon::instance(fake()->dateTimeBetween('+1 hour', '+1 year')), // Future date/time
            'address' => fake('ja_JP')->address, // Fake Japanese address
            'prefecture' => fake()->randomElement($prefectures),
            'latitude' => fake()->latitude(34, 36), // Latitude around central Japan
            'longitude' => fake()->longitude(135, 140), // Longitude around central Japan
            'acceptable_radius' => fake()->numberBetween(100, 1999), // Radius
            'status' => $status,
            'fee' => fake()->optional(0.7, 0)->numberBetween(0, 5000), // Optional fee, 0-5000 yen
            'capacity' => $capacity,
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }

     /**
     * Indicate that the game is recruiting.
     */
    public function recruiting(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => '募集中',
        ]);
    }

     /**
     * Indicate that the game is full.
     */
    public function full(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => '満員',
            // If full, participant count should equal capacity. This might need to be set after creation.
        ]);
    }

     /**
     * Indicate that the game is finished.
     */
    public function finished(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => '開催済み',
            'game_date_time' => Carbon::instance(fake()->dateTimeBetween('-1 month', '-2 hours')), // Past date
        ]);
    }

     /**
     * Indicate that the game is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => '中止',
        ]);
    }
}