<?php

namespace Database\Factories;

use App\Models\User; // User model
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash; // For hashing passwords
use Illuminate\Support\Str; // For Str::random

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    protected $model = User::class; // Link to the User model

    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Define how to generate fake data for each field
        return [
            // user_id is automatically generated by the model's boot method
            'email' => fake()->unique()->safeEmail(), // Generate unique fake email
            'email_verified_at' => now(), // Assume verified for factories
            'password' => static::$password ??= Hash::make('password'), // Default password 'password', hashed
            'nickname' => fake()->unique()->regexify('[a-zA-Z0-9あ-んア-ン一-?]{4}'), // Generate unique 4-char nickname
            'remember_token' => Str::random(10), // If using web sessions
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null, // Default to not soft-deleted
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }

    /**
     * Indicate that the user is soft-deleted.
     */
    public function deleted(): static
    {
        return $this->state(fn (array $attributes) => [
            'deleted_at' => now(),
        ]);
    }
}